<!-- A barra de navegação -->
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nossa Loja</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="../style.css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap"
        rel="stylesheet">
    


</head>
<body>>


<nav class="navbar">
    <div class="navbar-container">
        
        <!-- Logo e Título do Site -->
        <a href="index.php" class="logo">
            <img 
                src="imagens/logo.png" 
                alt="Logo" 
                class="logo-img"
                onerror="this.onerror=null;this.src='https://placehold.co/64x64/6366f1/white?text=Logo';> </a>

        <!-- Links de Navegação (Desktop) -->
        <ul class= "nav-links">
            <li><a href="index.php">Início</a></li>
            <li><a href="carrinho.php">Carrinho</a></li>
            <li><a href="contato.php">Contato</a></li>
<li><a href=" ">Login</a></li>
        </ul>

        <!-- Botão de Menu (Mobile) -->
        <div class="menu-icon">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>

    </div>
</nav>
</body>
</html>